### ISSUE TITLE
!! Bang-Bang operator causes error: Error in enquo(expr) : object 'x' not found

### ISSUE THREAD

**Issue by yogat3ch** [burchill/catchr#4]
Hi @burchill,
I've been thoroughly making use of `catchr` thanks to the info you provided in the [issue over on `furrr`](https://github.com/DavisVaughan/furrr/issues/49), thank you for cluing me into this useful package and for your dedicated effort in creating and maintaining it!

I've just encountered a somewhat bizarre error when using `catchr` to surface message from background processes using the implementation you provided. The bang bang `!!` operator just doesn't seem to work when `catch` is used!

Here's a reprex to illustrate:
```
write_to_file <- function(cond) {
  cond_class <- class(cond)[1]
  msg <- paste(cond_class, ":", cond$message)
  write(msg, file = "outlog", append=TRUE)
}

catch <- catchr::make_catch_fn(
  warning = c(write_to_file, muffle),
  message = c(write_to_file, muffle),
  error   = c(write_to_file, catchr::exit_with("Returned error!"))
)
cl <- parallel::makeCluster(2)
future::plan(future::cluster, workers = cl)

.d <- data.frame(time = rnorm(5), t2 = rnorm(5))
`!!` <- rlang::`!!`
`%>%` <- magrittr::`%>%`
# With normal furrr it's fine
furrr::future_imap(1:2, ~{
  .t <- "time"
  .ts <- rlang::sym(.t)
  .d %>% 
    dplyr::select(!!.ts)
})
# But with catchr the bang bang causes an error
furrr::future_imap(1:2, ~catch({
  .t <- "time"
  .ts <- rlang::sym(.t)
  .d %>% 
    dplyr::select(!!.ts)
}))

parallel::stopCluster(cl)
```
>Error in enquo(expr) : object '.ts' not found

I should also mention that apparently there's a new `immediateMessage` class in `future` functionality that allows messages to be surfaced to the console from background processes. You might already know about it, but if you haven't I just recently tagged you again on the [issue](https://github.com/DavisVaughan/furrr/issues/49) where you informed me about `catchr` where Davis Vaughan and Henrik Bengtsson shared it with me. I feel like it's info that is likely useful you and this package.

Here's my sessionInfo JIC you need it:
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.3     AlpacaforR_1.0.0     printr_0.1           dplyr_1.0.0          magrittr_1.5        
[6] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5.2         HDA_0.0.0.9000       catchr_0.2.2         pillar_1.4.6.9000    compiler_3.5.3      
 [6] tools_3.5.3          digest_0.6.25.1      packrat_0.5.0        bit_1.1-15.2         lubridate_1.7.9     
[11] jsonlite_1.7.0       RSQLite_2.2.0.9000   memoise_1.1.0        lifecycle_0.2.0.9000 tibble_3.0.3.9000   
[16] pkgconfig_2.0.3      rlang_0.4.7.9000     DBI_1.1.0            rstudioapi_0.11      parallel_3.5.3      
[21] xfun_0.15.1          furrr_0.1.0.9002     httr_1.4.1           stringr_1.4.0        knitr_1.29.3        
[26] globals_0.12.5       generics_0.0.2       vctrs_0.3.2          bit64_0.9-7          websocket_1.1.0     
[31] tidyselect_1.1.0     glue_1.4.1.9000      listenv_0.8.0        R6_2.4.1             tidyr_1.1.0         
[36] purrr_0.3.4.9000     blob_1.2.1           codetools_0.2-16     ellipsis_0.3.1       future_1.18.0       
[41] stringi_1.4.7        crayon_1.3.4   
```

**Comment by burchill** [comment]
So it looks like we've found ourselves what could be a `rlang` bug.  The issue doesn't seem to be in _my_ code (whew, close one). Check this out and tell me if you get the same type of error:

```r
fn <- function(expr) {
  rlang::enquo(expr)
}
fn({
  t <- "time"
  t2 <- rlang::sym(t)
  rlang::quo(!!t2)
})
```

It looks like it has something to do with `enquo()` trying to turn an expression with the bang-bang operator into a quosure. This definitely isn't the behavior I would expect from `rlang`, so we'd better file an issue with their repo. Unless you'd like to do it yourself, I'll file a bug report with them and see if I can get to the bottom of it.

Thanks for tagging me on the issue, I'm blown away by how Henrik keeps on packing amazing features into his code (to the point where it seems like they're hard to keep track of!).  I've actually been looking for a good progress tracker (for a new package I've been working on), so the `progressr` package seems great to know about as well. 

I think the use cases for `catchr` are being chipped away a little bit as time goes on by `future` and other packages, but I still plan on maintaining it, especially while people continue to use it. Thanks for bringing this bug to my attention, and feel free to bring up any other problems/improvements you run into!

**Comment by burchill** [comment]
Can you try installing the dev version (`devtools::install_github("burchill/catchr", ref="devel")`) and see if this problem still exists for you/if you have any other problems?

If it seems good, I'll release a new version with the fix.

**Comment by yogat3ch** [comment]
Seems to work fine now! Much gratitude to you for rolling out the fix so quickly and to Lionel for giving guidance on the `rlang` behavior that was creating the issue!
